<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BrandRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BrandRepository extends EntityRepository
{
    public function getFirstBrand($brand)
    {
        return $this->createQueryBuilder('b')
            ->select('b')
            ->leftJoin('t.brands', 'tb')
            ->where('tb = :brand')
            ->setParameter('brand', $brand)
            ->getQuery()->getResult()
            ;
    }
}
