<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TemplateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TemplateRepository extends EntityRepository
{
    public function getTemplatesByBrand($brand)
    {
        return $this->createQueryBuilder('t')
            ->select('t')
            ->leftJoin('t.brands', 'tb')
            ->where('tb = :brand')
            ->setParameter('brand', $brand)
            ->getQuery()->getResult();
        ;
    }
}
