documentation:
    resource: "documentation/routing.yml"
    prefix: /documentation

download:
    resource: "download/routing.yml"
    prefix: /download

editor:
    resource: "editor/routing.yml"
    prefix: /

